import type { Dataset, Policy, ApprovalRequest } from './types';

export const DOMAINS = [
  { value: 'credit_risk', label: 'Credit Risk', description: 'Credit exposure, ratings, loan portfolios' },
  { value: 'aml_fcc', label: 'AML/FCC', description: 'Anti-money laundering, fraud, compliance monitoring' },
  { value: 'finance', label: 'Finance/Reg Reporting', description: 'Financial statements, regulatory reports' },
  { value: 'treasury', label: 'Treasury/Markets', description: 'Trading, liquidity, market risk' },
  { value: 'retail', label: 'Retail/Channels', description: 'Customer accounts, transactions, channels' },
  { value: 'ops', label: 'Operations/Service', description: 'Operations metrics, service quality' },
] as const;

export const SAMPLE_DATASETS: Dataset[] = [
  {
    id: 'ds-001',
    name: 'customer_transactions',
    domain: 'retail',
    owner: 'retail-data-team',
    description: 'Daily customer transaction records including deposits, withdrawals, and transfers',
    schema: [
      { name: 'transaction_id', type: 'string', nullable: false, pii: false },
      { name: 'customer_id', type: 'string', nullable: false, pii: true, description: 'Hashed customer identifier' },
      { name: 'account_number', type: 'string', nullable: false, pii: true },
      { name: 'transaction_type', type: 'string', nullable: false, pii: false },
      { name: 'amount', type: 'decimal', nullable: false, pii: false },
      { name: 'currency', type: 'string', nullable: false, pii: false },
      { name: 'timestamp', type: 'timestamp', nullable: false, pii: false },
      { name: 'channel', type: 'string', nullable: false, pii: false },
    ],
    piiLevel: 'high',
    jurisdiction: 'multi',
    freshnessSLA: 1,
    lastRefresh: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    tags: ['transactions', 'retail', 'real-time'],
    recordCount: 15_234_567,
  },
  {
    id: 'ds-002',
    name: 'loan_portfolio',
    domain: 'credit_risk',
    owner: 'credit-risk-team',
    description: 'Comprehensive loan portfolio with risk ratings and exposure data',
    schema: [
      { name: 'loan_id', type: 'string', nullable: false, pii: false },
      { name: 'borrower_id', type: 'string', nullable: false, pii: true },
      { name: 'loan_amount', type: 'decimal', nullable: false, pii: false },
      { name: 'outstanding_balance', type: 'decimal', nullable: false, pii: false },
      { name: 'risk_rating', type: 'string', nullable: false, pii: false },
      { name: 'default_probability', type: 'decimal', nullable: true, pii: false },
      { name: 'origination_date', type: 'date', nullable: false, pii: false },
      { name: 'maturity_date', type: 'date', nullable: false, pii: false },
      { name: 'collateral_value', type: 'decimal', nullable: true, pii: false },
    ],
    piiLevel: 'low',
    jurisdiction: 'US',
    freshnessSLA: 24,
    lastRefresh: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    tags: ['loans', 'credit', 'risk'],
    recordCount: 234_567,
  },
  {
    id: 'ds-003',
    name: 'aml_alerts',
    domain: 'aml_fcc',
    owner: 'compliance-team',
    description: 'AML system alerts requiring investigation and disposition',
    schema: [
      { name: 'alert_id', type: 'string', nullable: false, pii: false },
      { name: 'customer_id', type: 'string', nullable: false, pii: true },
      { name: 'alert_type', type: 'string', nullable: false, pii: false },
      { name: 'risk_score', type: 'integer', nullable: false, pii: false },
      { name: 'triggered_date', type: 'timestamp', nullable: false, pii: false },
      { name: 'status', type: 'string', nullable: false, pii: false },
      { name: 'assigned_analyst', type: 'string', nullable: true, pii: false },
      { name: 'disposition', type: 'string', nullable: true, pii: false },
      { name: 'sar_filed', type: 'boolean', nullable: true, pii: false },
    ],
    piiLevel: 'high',
    jurisdiction: 'US',
    freshnessSLA: 4,
    lastRefresh: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    tags: ['aml', 'compliance', 'alerts'],
    recordCount: 8_945,
  },
  {
    id: 'ds-004',
    name: 'regulatory_reports',
    domain: 'finance',
    owner: 'finance-reporting-team',
    description: 'Consolidated regulatory reports submitted to authorities',
    schema: [
      { name: 'report_id', type: 'string', nullable: false, pii: false },
      { name: 'report_type', type: 'string', nullable: false, pii: false },
      { name: 'reporting_period', type: 'string', nullable: false, pii: false },
      { name: 'jurisdiction', type: 'string', nullable: false, pii: false },
      { name: 'submission_date', type: 'date', nullable: false, pii: false },
      { name: 'status', type: 'string', nullable: false, pii: false },
      { name: 'total_assets', type: 'decimal', nullable: false, pii: false },
      { name: 'total_liabilities', type: 'decimal', nullable: false, pii: false },
    ],
    piiLevel: 'none',
    jurisdiction: 'multi',
    freshnessSLA: 168,
    lastRefresh: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    tags: ['regulatory', 'finance', 'reports'],
    recordCount: 1_234,
  },
  {
    id: 'ds-005',
    name: 'trading_positions',
    domain: 'treasury',
    owner: 'treasury-team',
    description: 'Current trading positions across all asset classes',
    schema: [
      { name: 'position_id', type: 'string', nullable: false, pii: false },
      { name: 'security_id', type: 'string', nullable: false, pii: false },
      { name: 'asset_class', type: 'string', nullable: false, pii: false },
      { name: 'quantity', type: 'decimal', nullable: false, pii: false },
      { name: 'market_value', type: 'decimal', nullable: false, pii: false },
      { name: 'book_value', type: 'decimal', nullable: false, pii: false },
      { name: 'unrealized_pnl', type: 'decimal', nullable: false, pii: false },
      { name: 'as_of_date', type: 'date', nullable: false, pii: false },
    ],
    piiLevel: 'none',
    jurisdiction: 'US',
    freshnessSLA: 1,
    lastRefresh: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    tags: ['trading', 'treasury', 'positions'],
    recordCount: 45_678,
  },
];

export const SAMPLE_POLICIES: Policy[] = [
  {
    id: 'pol-001',
    name: 'PII Access Requires Approval',
    type: 'access',
    condition: 'dataset.piiLevel == "high"',
    action: 'require_approval',
    scope: {
      piiLevels: ['high'],
    },
    approvers: ['compliance-team', 'data-governance-team'],
  },
  {
    id: 'pol-002',
    name: 'Cross-Jurisdiction Query Block',
    type: 'access',
    condition: 'query.datasets.jurisdictions.count > 1 AND user.role != "admin"',
    action: 'require_approval',
    scope: {
      jurisdictions: ['multi'],
    },
    approvers: ['legal-team', 'compliance-team'],
  },
  {
    id: 'pol-003',
    name: 'Production Pipeline Deployment',
    type: 'approval',
    condition: 'pipeline.target == "production"',
    action: 'require_approval',
    scope: {},
    approvers: ['data-engineering-lead', 'domain-owner'],
  },
  {
    id: 'pol-004',
    name: 'AML Data Access Restriction',
    type: 'access',
    condition: 'dataset.domain == "aml_fcc"',
    action: 'require_approval',
    scope: {
      domains: ['aml_fcc'],
    },
    approvers: ['aml-team-lead'],
  },
];

export const SAMPLE_APPROVALS: ApprovalRequest[] = [
  {
    id: 'apr-001',
    type: 'pipeline_deploy',
    requester: 'john.analyst',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    description: 'Deploy daily credit risk aggregation pipeline to production',
    riskLevel: 'high',
    evidencePackId: 'evd-001',
    status: 'pending',
    details: {
      pipelineName: 'credit_risk_daily_agg',
      sourceDatasets: ['loan_portfolio', 'collateral_valuations'],
      targetDataset: 'credit_risk_summary',
      testsPass: true,
      dqChecksPass: true,
    },
  },
  {
    id: 'apr-002',
    type: 'pii_access',
    requester: 'sarah.analyst',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    description: 'Request access to customer transaction PII for fraud investigation',
    riskLevel: 'high',
    evidencePackId: 'evd-002',
    status: 'pending',
    details: {
      datasetName: 'customer_transactions',
      piiFields: ['customer_id', 'account_number'],
      justification: 'Fraud case #12345 requires customer-level transaction analysis',
      duration: '7 days',
    },
  },
  {
    id: 'apr-003',
    type: 'dataset_onboard',
    requester: 'mike.engineer',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    description: 'Onboard new merchant payment dataset from acquiring system',
    riskLevel: 'medium',
    evidencePackId: 'evd-003',
    status: 'approved',
    approver: 'data.governance',
    approvalTimestamp: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    approvalComment: 'Approved. Ensure PII masking is enabled before production.',
    details: {
      datasetName: 'merchant_payments',
      domain: 'retail',
      piiLevel: 'low',
      recordCountEstimate: 500000,
    },
  },
];

export const SAMPLE_QUERIES = [
  {
    domain: 'credit_risk',
    question: 'What is the total outstanding balance for high-risk loans?',
    expectedDatasets: ['loan_portfolio'],
  },
  {
    domain: 'aml_fcc',
    question: 'Show me all open AML alerts with risk score above 80',
    expectedDatasets: ['aml_alerts'],
  },
  {
    domain: 'retail',
    question: 'What is the daily transaction volume by channel for the last 7 days?',
    expectedDatasets: ['customer_transactions'],
  },
  {
    domain: 'treasury',
    question: 'Calculate unrealized P&L by asset class',
    expectedDatasets: ['trading_positions'],
  },
  {
    domain: 'finance',
    question: 'What regulatory reports are due this month?',
    expectedDatasets: ['regulatory_reports'],
  },
];
